version: '3.1'

services:
  backend:
    build: backend
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      APP_USER: list
      APP_PWD: list
      DB_NAME: list
    volumes:
      - database:/data/initdb
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  database: