version: '3.1'

services:
  frontend:
    build: frontend
    ports:
      - "3000:80"
  backend:
    build: backend
    ports:
      - "4000:4000"
  db:
    build: database
    restart: always
    environment:
      POSTGRES_PASSWORD: list
      POSTGRES_USER: list
      POSTGRES_DB: list
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: